### ISSUE TITLE
Add support for data-domains

### ISSUE THREAD

**Issue by mattsbanner** [phiilu/gatsby-plugin-umami#2]
It would be handy if this plugin supported passing through the `data-domains` property.

https://umami.is/docs/tracker-config

**Comment by ohrie** [comment]
I've created a PR for this: #3 
Now waiting for feedback of @phiilu

**Comment by phiilu** [comment]
sorry @mattsbanner I did not see this issue.  thx @ohrie I commented on your PR

**Comment by phiilu** [comment]
@all-contributors please add @mattsbanner for bug

**Comment by phiilu** [comment]
Sorry for the very delayed merge of your #3 PR!
