### ISSUE TITLE
Update to support Umami v2 Changes

### ISSUE THREAD

**Issue by BradNut** [phiilu/gatsby-plugin-umami#8]
Will there be an update for the new Umami Analytics v2 changes?
https://umami.is/docs/migrate-v1-v2

Specifically this line: The tracker script has been renamed from umami.js to script.js.

I would assume the Gatsby Plugin would need to insert the new script endpoint.

**Comment by phiilu** [comment]
I will try my best to release a updated version, but I would really appreciate if someone else could create a PR and I am happy to review it and test it. 

I am at the moment not working on any Gatsby Projects (and did not for months 😅) so I am a bit dated when it comes to Gatsby

**Comment by phiilu** [comment]
I have looked into the changes, but I think the gatsby-plugin-umami already supports V2 🎉, because you can already configure the `src` of the script tag. 

I only update the README so that it is now referring to `script.js` instead of `umami.js`
